# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_btc', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
            ],
        ),
    ]
